%% Copyright 2014 MERCIER David
function customized_menu(parent)
%% Setting of customized menu
% parent: handle of the GUI

yaml_menu = uimenu(parent, 'Label', 'YAML File');

uimenu(yaml_menu, ...
    'Label', ...
    'Edit YAML config. file', ...
    'Callback', ...
    'edit_YAMLconfigFile');

uimenu(yaml_menu, ...
    'Label', ...
    'Load YAML config. file', ...
    'Callback', ...
    ['gui = guidata(gcf);',...
    '[gui.config.indenter, gui.config.data, '...
    'gui.config.numerics] = load_YAMLconfigFile;' ...
    'guidata(gcf, gui);']);

uimenu(yaml_menu, ...
    'Label', ...
    'YAML website', ...
    'Callback', ...
    'web(''http://yaml.org/'',''-browser'')');

uimenu(yaml_menu, ...
    'Label', ...
    'YAML Matlab website', ...
    'Callback', ...
    'web(''http://code.google.com/p/yamlmatlab/'',''-browser'')');

help_menu = uimenu(parent, 'Label', 'Help NIMS_Toolbox');

uimenu(help_menu, ...
    'Label', ...
    'HTML Documentation', ...
    'Callback', ...
    'gui = guidata(gcf); web(gui.config.url_help,''-browser'')');

uimenu(help_menu, ...
    'Label', ...
    'PDF Documentation', ...
    'Callback', ...
    'gui = guidata(gcf); web(gui.config.pdf_help,''-browser'')');

end