%% Copyright 2014 MERCIER David
function indenters_properties_GUI
%% Function used to get properties of the selected indenter
gui = guidata(gcf);

%% Properties of the indenter tip
gui.handles.title_indenter_ang_prop_GUI = uicontrol(...
    'Parent', gui.handles.bg_indenter_tip_GUI,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0. 0.65 0.4 0.35],...
    'String', 'Angle eq. of the conical tip :',...
    'HorizontalAlignment', 'left');

gui.handles.value_indenter_ang_prop_GUI = uicontrol(...
    'Parent', gui.handles.bg_indenter_tip_GUI,...
    'Units', 'normalized',...
    'Style', 'edit',...
    'Position', [0.35 0.8 0.1 0.2],...
    'String', 45,...
    'Callback', 'get_and_plot');

gui.handles.unit_indenter_ang_prop_GUI = uicontrol(...
    'Parent', gui.handles.bg_indenter_tip_GUI,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.45 0.65 0.04 0.35],...
    'String', '°',...
    'HorizontalAlignment', 'center');

gui.handles.title_indenter_def_prop_GUI = uicontrol(...
    'Parent', gui.handles.bg_indenter_tip_GUI,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.6 0.65 0.35 0.35],...
    'String', 'Tip defect :',...
    'HorizontalAlignment', 'left');

gui.handles.value_indenter_def_prop_GUI = uicontrol(...
    'Parent', gui.handles.bg_indenter_tip_GUI,...
    'Units', 'normalized',...
    'Style', 'edit',...
    'Position', [0.75 0.8 0.1 0.2],...
    'String', 1,....
    'Callback', 'get_and_plot');

gui.handles.unit_indenter_def_prop_GUI = uicontrol(...
    'Parent', gui.handles.bg_indenter_tip_GUI,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.85 0.65 0.08 0.35],...
    'String', 'nm',...
    'HorizontalAlignment','center');

% Function area
gui.handles.title_area_function_GUI = uicontrol(...
    'Parent', gui.handles.bg_indenter_tip_GUI,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0 0.325 0.9 0.325],...
    'String', 'Coefficients of the area function :',...
    'HorizontalAlignment', 'left');

gui.handles.title_C0_GUI = uicontrol(...
    'Parent', gui.handles.bg_indenter_tip_GUI,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0 0.1 0.08 0.2],...
    'String', 'C0 :',...
    'HorizontalAlignment', 'left');

gui.handles.value_C0_GUI = uicontrol(...
    'Parent', gui.handles.bg_indenter_tip_GUI,...
    'Units', 'normalized',...
    'Style', 'edit',...
    'Position', [0.05 0.1 0.1 0.2],...
    'String', 24.56,...
    'Callback', 'get_and_plot');

gui.handles.title_C1_GUI = uicontrol(...
    'Parent', gui.handles.bg_indenter_tip_GUI,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.2 0.1 0.08 0.2],...
    'String', 'C1 :',...
    'HorizontalAlignment', 'left');

gui.handles.value_C1_GUI = uicontrol(...
    'Parent', gui.handles.bg_indenter_tip_GUI,...
    'Units', 'normalized',...
    'Style', 'edit',...
    'Position',[0.25 0.1 0.1 0.2],...
    'String', 0,...
    'Callback', 'get_and_plot');

gui.handles.title_C2_GUI = uicontrol(...
    'Parent', gui.handles.bg_indenter_tip_GUI,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.4 0.1 0.08 0.2],...
    'String', 'C2 :',...
    'HorizontalAlignment', 'left');

gui.handles.value_C2_GUI = uicontrol(...
    'Parent', gui.handles.bg_indenter_tip_GUI,...
    'Units', 'normalized',...
    'Style', 'edit',...
    'Position', [0.45 0.1 0.1 0.2],...
    'String', 0,...
    'Callback', 'get_and_plot');

gui.handles.title_C3_GUI = uicontrol(...
    'Parent', gui.handles.bg_indenter_tip_GUI,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.6 0.1 0.08 0.2],...
    'String', 'C3 :',...
    'HorizontalAlignment', 'left');

gui.handles.value_C3_GUI = uicontrol(...
    'Parent', gui.handles.bg_indenter_tip_GUI,...
    'Units', 'normalized',...
    'Style', 'edit',...
    'Position', [0.65 0.1 0.1 0.2],...
    'String', 0,...
    'Callback', 'get_and_plot');

gui.handles.title_C4_GUI = uicontrol(...
    'Parent', gui.handles.bg_indenter_tip_GUI,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.8 0.1 0.08 0.2],...
    'String', 'C4 :',...
    'HorizontalAlignment', 'left');

gui.handles.value_C4_GUI = uicontrol(...
    'Parent', gui.handles.bg_indenter_tip_GUI,...
    'Units', 'normalized',...
    'Style', 'edit',...
    'String', 0,...
    'Position', [0.85 0.1 0.1 0.2],...
    'Callback', 'get_and_plot');

guidata(gcf, gui);

end