%% Copyright 2014 MERCIER David
function [h_title, h_thickTitle, h_thickString, h_thickUnit, ...
    h_youngTitle, h_youngString, h_youngUnit, h_poissonTitle, h_poissonString, ... 
    h_hardnessTitle, h_hardnessString, h_hardnessUnit] = ...
    thin_films_properties_GUI(parent, position, stringTitle)
%% Function used to set the properties of the thin films and the substrate

p = position;

%% Title
h_title = uicontrol(...
    'Parent', parent, 'Units', 'normalized', 'Style', 'text',...
    'Position', position, 'String', stringTitle);

%% Thickness
h_thickTitle = uicontrol(...
    'Parent', parent, 'Units', 'normalized', 'Style', 'text',...
    'Position', [p(1)+0.15 p(2) p(3)-0.05 p(4)],...
    'String', 't ='); 

h_thickString = uicontrol(...
    'Parent', parent, 'Units', 'normalized', 'Style', 'edit',...
    'Position', [p(1)+0.19 p(2) p(3)-0.06 p(4)+0.2],...
    'String', 500);

h_thickUnit = uicontrol(...
    'Parent', parent, 'Units', 'normalized', 'Style', 'text',...
    'Position', [p(1)+0.27 p(2) p(3)-0.06 p(4)],...
    'String', 'nm');

%% Young's modulus
h_youngTitle = uicontrol(...
    'Parent', parent, 'Units', 'normalized', 'Style', 'text',...
    'Position', [p(1)+0.34 p(2) p(3)-0.03 p(4)],...
    'String', '/ YM =');

h_youngString = uicontrol(...
    'Parent', parent, 'Units', 'normalized', 'Style', 'edit',...
    'Position', [p(1)+0.43 p(2) p(3)-0.06 p(4)+0.2],...
    'String', 100);

h_youngUnit = uicontrol(...
    'Parent', parent, 'Units', 'normalized', 'Style', 'text',...
    'Position', [p(1)+0.51 p(2) p(3)-0.06 p(4)],...
    'String', 'GPa');

%% Poisson's ratio
h_poissonTitle = uicontrol(...
    'Parent', parent, 'Units', 'normalized', 'Style', 'text',...
    'Position', [p(1)+0.58 p(2) p(3)-0.03 p(4)],...
    'String', '/ PR =');

h_poissonString = uicontrol(...
    'Parent', parent, 'Units', 'normalized', 'Style', 'edit',...
    'Position', [p(1)+0.67 p(2) p(3)-0.06 p(4)+0.2],...
    'String', 0.3);

%% Hardness
h_hardnessTitle = uicontrol(...
    'Parent', parent, 'Units', 'normalized', 'Style', 'text',...
    'Position', [p(1)+0.75 p(2) p(3)-0.03 p(4)],...
    'String', '/ H =');

h_hardnessString = uicontrol(...
    'Parent', parent, 'Units', 'normalized', 'Style', 'edit',...
    'Position', [p(1)+0.82 p(2) p(3)-0.06 p(4)+0.2],...
    'String', 1);

h_hardnessUnit = uicontrol(...
    'Parent', parent, 'Units', 'normalized', 'Style', 'text',...
    'Position', [p(1)+0.9 p(2) p(3)-0.06 p(4)],...
    'String', 'GPa');

%% Settings
set([h_title, h_thickTitle, h_youngTitle, h_poissonTitle, h_hardnessTitle], ...
    'HorizontalAlignment', 'left');

set([h_thickString, h_youngString, h_poissonString, h_hardnessString], ...
    'Callback', 'get_and_plot');

set([h_thickUnit, h_youngUnit, h_hardnessUnit], ...
    'HorizontalAlignment', 'center');

end