%% Copyright 2014 MERCIER David
function model_gao
%% Function used to calculate Young's modulus in bilayer system with
% the model of Gao et al. (1992) (for flat cylindrical indentation test...)
% see also Hay et al. (2011)
% Errors for phigao0 in Fischer-Cripps "Nanoindentation 2nd Ed.".

gui = guidata(gcf);

x = gui.results.t_corr./gui.results.ac;

gui.data.phigao1 = (2/pi).*atan(x)+(x./pi).*log((1+(x).^2)./(x).^2);


gui.data.nuc = 1-(((1-gui.data.nus)*(1-gui.data.nuf)) ./ ...
    (1-(1-gui.data.phigao1)*gui.data.nuf-(gui.data.phigao1*gui.data.nus)));

gui.data.phigao0 = (2/pi).*atan(x) + ((1./(2.*pi.*(1-gui.data.nuc))) .* ...
    (((1-2*gui.data.nuc).*x.*log(1+(1./x).^2)) - (x./(1+(x).^2))));

bilayer_model = @(Ef_red_sol, x) ...
    (1e-9*((((1e9*Ef_red_sol)-gui.data.Es_red) .* ...
    gui.data.phigao0)+gui.data.Es_red));

% Make a starting guess
gui.results.Ef_red_sol0 = ...
    str2double(get(gui.handles.value_youngfilm1_GUI, 'String')) / ...
    (1-gui.data.nuf.^2);

OPTIONS = optimset('lsqcurvefit');
OPTIONS = optimset(OPTIONS, 'TolFun',  1e-20);
OPTIONS = optimset(OPTIONS, 'TolX',    1e-20);
OPTIONS = optimset(OPTIONS, 'MaxIter', 10000);
[gui.results.Ef_red_sol_fit, ...
    gui.results.resnorm, ...
    gui.results.residual, ...
    gui.results.exitflag, ...
    gui.results.output, ...
    gui.results.lambda, ...
    gui.results.jacobian] =...
    lsqcurvefit(bilayer_model, gui.results.Ef_red_sol0, x, ...
    gui.results.Esample_red, ...
    0, 1000, OPTIONS);

gui.results.Ef_sol_fit = gui.results.Ef_red_sol_fit * ...
    (1-gui.data.nuf^2);

gui.results.Em_red = 1e-9 * ...
    ((((1e9*gui.results.Ef_red_sol_fit) - gui.data.Es_red) .* ...
    gui.data.phigao0) + gui.data.Es_red);

gui.results.Ef_red = 1e-9 * ...
    ((((1e9.*gui.results.Esample_red)-gui.data.Es_red) ./ ...
    gui.data.phigao0) + gui.data.Es_red);

guidata(gcf, gui);

end