%% Copyright 2014 MERCIER David
function model_jung(OPTIONS)
%% Function used to calculate Young's modulus in bilayer system with
% the model of Jung et al. (2004)
gui = guidata(gcf);

x = gui.results.hc./gui.results.t_corr;
x = checkValues(x);

% Minimum and maximum boundaries for the constant alpha
A_Jung = gui.config.numerics.A_Jung;
B_Jung = gui.config.numerics.B_Jung;

L_Jung = sigmoidal_jung(x, A_Jung, B_Jung);

% A(1) = Ef_red
bilayer_model = @(A, x) ...
    (1e-9*(gui.data.Es_red * (1e9*A(1) ./ gui.data.Es_red)...
    .^L_Jung));

% Make a starting guess
gui.results.A0 = gui.data.Ef_red;

[gui.results.Ef_red_sol_fit, ...
    gui.results.resnorm, ...
    gui.results.residual, ...
    gui.results.exitflag, ...
    gui.results.output, ...
    gui.results.lambda, ...
    gui.results.jacobian] =...
    lsqcurvefit(bilayer_model, gui.results.A0, x, ...
    gui.results.Esample_red, ...
    gui.config.numerics.Min_YoungModulus, ...
    gui.config.numerics.Max_YoungModulus, ...
    OPTIONS);

gui.results.Em_red = ...
    (1e-9*(gui.data.Es_red * (1e9*gui.results.Ef_red_sol_fit ./ gui.data.Es_red)...
    .^L_Jung));

gui.results.Ef_red = 1e-9*(((1e9.*gui.results.Esample_red)./...
    (1./gui.data.Es_red).^(L_Jung-1)).^(1./L_Jung));

guidata(gcf, gui);

end